"""
Django settings for first_devops project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(a$2bfsw(k@vg-9h@taulux)7=72cm+nc7p1+avr5sb*shg)il'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'scanhosts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'first_devops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'first_devops.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'devopsProject',
        'USER': 'devops',
        'PASSWORD': 'westos',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

# 日志管理的配置
LOGGING = {
    'version': 1,
    # disable_existing_loggers是否禁用已经存在的logger实例。默认值是True.
    'disable_existing_loggers': False,
    # formatters: 定义输出的日志格式。
    'formatters': {
        'verbose': {
            # 格式化属性查看资料：https://docs.python.org/3/library/logging.html#logrecord-attributes
            'format': '{levelname} {asctime} {module} : {lineno} {message}',
            # 变量的风格
            'style': '{',
            # 日期显示格式
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    # handlers定义处理器。
    'handlers': {
        'file': {
            # 日志处理级别
            'level': 'INFO',
            # 日志处理类, 详细的请查看网站: https://docs.python.org/3/library/logging.handlers.html
            'class': 'logging.FileHandler',
            # 日志处理后输出格式
            'formatter': 'verbose',
            # 记录日志的文件名, 存储在当前项目目录下的devops.log文件
            'filename': os.path.join(BASE_DIR, 'devops.log')
        },
    },
    # loggers定义logger实例。
    'loggers': {
        'django': {
            # 对应的handles对象列表
            'handlers': ['file'],
            # logger实例输出的日志级别
            'level': 'INFO',
            # 日志是否向上级传递。True 向上级传，False 不向上级传。
            'propagate': True,
        },
    }
}

# 邮件配置
EMAIL_HOST = 'smtp.qq.com'
EMAIL_HOST_USER = '976131979@qq.com'
EMAIL_HOST_PASSWORD = 'lnrsvqgoqntpbeei'
EMAIL_PORT = 465
EMAIL_SUBJECT_PREFIX = 'Python开发社区'
EMAIL_USE_SSL = True


USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
